version: '2'
services:
  mediatomb:
    build: docker/mediatomb
    network_mode: host
    environment:
      - DISPLAY = :0.0
    volumes:
      - /home/paul/Videos:/home
      - ./.data:/var/lib/mediatomb
      - ./etc/mediatomb/config.xml:/etc/mediatomb/config.xml
      - ./overlay.sh:/usr/local/bin/overlay.sh
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/paul/.Xauthority:/root/.Xauthority
    volumes_from:
      - db


  db:
    image: mariadb:latest
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=pwgen
      - MYSQL_DATABASE=mediatomb
      - MYSQL_USER=mediatomb
      - MYSQL_PASSWORD=pwgen
    volumes:
      - .data/:/var/lib/mysql

  zabbix:
    image: monitoringartist/zabbix-xxl:latest

    ports:
      - 80:80

    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
      - XXL_zapix=true
      - XXL_grapher=true

    links:
      - zabbix-db:zabbix.db

    volumes:
      -  ./etc/zabbix_externalscripts:/usr/local/share/zabbix/externalscripts

  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password

  nginx:
    image: nginx:latest
    ports:
      - 81:80
    volumes:
      - ./etc/nginx/sites-enabled/default:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    links:
      - php

  php:
    image: php:fpm-alpine
    volumes:
      - ./nginx:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Kiev

  transmission:
    build: docker/transmission
    volumes:
      - ./etc/transmission-daemon/settings.json:/etc/transmission-daemon/settings.json
    volumes_from:
      - mediatomb
    network_mode: host